### ISSUE TITLE
Support any framerate

### ISSUE THREAD

**Issue by alexanderturinske** [CrystalComputerCorp/smpte-timecode#6]
This package puts a restriction on the framerate a video can have
`frameRate: number, optional
one of 23.976, 24, 25, 29.97, 30, 50, 59.94, or 60 is expected. 29.97 is assumed if the parameter is omitted.`

This restriction seems needless to me. Would there be an issue with removing the restriction on the framerate?

Relates to #1

**Comment by m1tk4** [comment]
This is more of a sanity check than anything else. Are you working with framerates other than those listed? If yes, what are they?

**Comment by alexanderturinske** [comment]
I encountered a framerate of `59.53` and `29.982` recently and, though it was an oddball, this library gave me an issue.

**Comment by adamthesax** [comment]
I too have seen some frame rates that are not in the whitelist provided above. I recognize this is a sanity check as well as making it easier to detect drop frames, but it could be limiting for some professional workflows.

**Comment by charlesritchea** [comment]
The issue for me is that framerates are often encoded as numerator and denominator like 30000/1001, so I would have to convert to your expected numbers (which floating point numbers shouldn't be used as keys in general in computing).

**Comment by m1tk4** [comment]
very good point. I am actually looking at changing the way they are specified to num/denom as well as we have a few corner cases when I think rounding it up gives us +-frame slop.

**Comment by thatmarvin** [comment]
@m1tk4 Would you accept a PR that removes this frame rate check against the list? I work for Frame.io and our customers do upload videos with various non-standard frame rates.

Would you also consider another PR that throws an error for invalid `frameRate`s instead of defaulting to `29.97`? This forces the call site to handle it explicitly instead of silently outputting a wrong timecode when the actual frame rate isn't `29.97`.

**Comment by m1tk4** [comment]
@thatmarvin I was actually thinking more in terms of allowing any numerator/denominator combination for specifying framerates, rather than throwing if it's not one of the predefined. Something along the lines of [30000,1001] passed as a parameter instead of 29.97, and then maybe having some predefined "constants" like

fr2997 = [30000,1001];
fr5994 = [60000,1001];

etc.

Then reworking all arithmetic so it deals with integers.

Thoughts?

**Comment by thatmarvin** [comment]
@m1tk4 That wouldn't be too useful for me, because I want to just pass in the frame rate directly from video metadata without modifying it. I'm not sure if it's entirely correct for the consumer to do something like "if (metadata.fps is 29.97 or 59.94) pass in exact fractions instead".

Also, using the less precise `29.97/59.94` hasn't actually been a problem for me.

**Comment by thatmarvin** [comment]
@m1tk4 Here's what I did to relax the check instead: https://github.com/Frameio/smpte-timecode/pull/2/files

**Comment by m1tk4** [comment]
@thatmarvin this look awesome, please submit the PR. I think this will be compatible with what I have in mind for nom/den calculations. Thanks!

**Comment by thatmarvin** [comment]
@m1tk4 Done! I also did https://github.com/Frameio/smpte-timecode/pull/1 if you're interested!

**Comment by m1tk4** [comment]
thank you!

**Comment by m1tk4** [comment]
Actually I had build failures with this - https://travis-ci.org/CrystalComputerCorp/smpte-timecode/builds/546961161 @thatmarvin - should both of your changes be applied at the same time? Do you mind resubmitting the PR's so they keep the tests successful?

If you're too busy I'll take a look at it over the weekend and reapply the PR once I figure out what needs to change in the tests.

**Comment by thatmarvin** [comment]
Oops sorry! I cherry-picked that commit but forgot that it's based on my own fork that removed the check against the list of allowed frame rates. Two ways to take care of this:

1. Add the fractions to the whitelist, or
2. Remove the whitelist check altogether: https://github.com/Frameio/smpte-timecode/pull/1/commits/88034fa58740270e1a062ea61c3b00fe90dcf292

**Comment by m1tk4** [comment]
This is resolved in 1.3.1
